[workspace]
authors = ["Miroslav Georgiev <miro.georgiev@gmail.com>"]
channels = ["conda-forge"]
name = "elenchus"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]
format = "black ."
check-format = "black --check ."

[dependencies]
python = ">=3.13.5,<3.14"
requests = ">=2.32.4,<3"
debugpy = ">=1.8.15,<2"
typer = ">=0.16.0,<0.17"
importlib-metadata = ">=8.7.0,<9"
black = ">=25.1.0,<26"
pyyaml = ">=6.0.1,<7"
pre-commit = ">=4.2.0,<5"
python-dotenv = ">=1.1.1,<2"
litellm = ">=1.75.0,<2"
ipython = ">=9.4.0,<10"
pytest = ">=8.4.1,<9"
pytest-cov = ">=6.2.1,<7"
pandas = ">=2.2.0,<3"
matplotlib = ">=3.8.0,<4"
seaborn = ">=0.13.0,<1"
scipy = ">=1.12.0,<2"

[feature.pycharm.dependencies]
pixi-pycharm = ">=0.0.8,<0.0.9"
