# Elenchus Configuration Example
# Copy this file to ~/.elenchus/config.yaml and modify as needed

# HumanEval dataset configuration
human_eval_url: "https://raw.githubusercontent.com/openai/human-eval/master/data/HumanEval.jsonl.gz"
output_dir: "generated_tests"
experiments_dir: "experiments"
max_iterations: 5

# LLM configuration
llm_model: "gpt-4"
llm_api_key: null  # Set your API key here or use environment variable ELENCHUS_LLM_API_KEY
llm_temperature: 0.1
llm_max_tokens: 2000
llm_provider: "openai"
llm_base_url: null  # Custom endpoint URL (optional)
llm_timeout: 30

# Logging configuration
log_level: "INFO"  # DEBUG, INFO, WARNING, ERROR, CRITICAL
log_file: null  # Log file path (optional)

# Experiment configuration
default_prompt_id: "default"
track_experiments: true 